general:
    worker:
        devices_per_job: 1

pipeline: [hpo, fully_train, benchmark_cifar10]

hpo:
    pipe_step:
        type: NasPipeStep

    dataset:
        type: Cifar10
        common:
            data_path: /cache/datasets/cifar10/
            batch_size: 256

    search_algorithm:
        type: BohbHpo
        policy:
            total_epochs: 2430
            repeat_times: 2
    
    search_space:
        type: SearchSpace
        hyperparameters:
            -   key: dataset.batch_size
                type: INT_CAT
                range: [64, 128, 256]
            -   key: trainer.optim.params.lr
                type: FLOAT_CAT
                range: [0.001, 0.003, 0.007, 0.01, 0.03, 0.07, 0.1]
            -   key: trainer.optim.type
                type: STRING
                range: ['Adam', 'SGD']
            -   key: trainer.optim.params.momentum
                type: FLOAT
                range: [0.8, 0.99]
        condition:
            -   key: condition_for_sgd_momentum
                child: trainer.optim.params.momentum
                parent: trainer.optim.type
                type: EQUAL
                range: ["SGD"]

    model:
        model_desc:
            modules: ["backbone", "head"]
            backbone:
                base_channel: 64
                downsample: [0, 0, 1, 0, 1, 0, 1, 0]
                base_depth: 18
                doublechannel: [0, 0, 1, 0, 1, 0, 1, 0]
                name: ResNetVariant
            head:
                num_classes: 10
                name: LinearClassificationHead
                base_channel: 512

    trainer:
        type: Trainer
        epochs: 1

    evaluator:
        type: Evaluator
        gpu_evaluator:
            type: GpuEvaluator
            metric:
                type: accuracy

fully_train:
    pipe_step:
        type: FullyTrainPipeStep
    dataset:
        ref: hpo.dataset
    model:
        ref: hpo.model
    trainer:
        ref: hpo.trainer
        load_checkpoint: True
        epochs: 200
        hps_file: "{local_base_path}/output/hpo/best_hps.json"

benchmark_cifar10:
    pipe_step:
        type: BenchmarkPipeStep
        models_folder: "{local_base_path}/output/fully_train/"
    dataset:
        type: Cifar10
    evaluator:
        type: Evaluator
        gpu_evaluator:
            type: GpuEvaluator
            metric:
                type: accuracy
