edvr:
  with_tsa: True
  num_deform_groups: 1
  loss_reduction: 'mean'
  loss_type: 'l1'
  impl: 'npu'
data:
  train_batch_size: 4
  train_data_queue_size: 64
  num_threads: 8
  read_mode: 'python'
solver:
  mix_precision: False
  xla: False
device: 'npu'
output_dir: 'outputs/edvr'
