general:
    worker:
        devices_per_job: -1

pipeline: [nas, fully_train]

nas:
    pipe_step:
        type: NasPipeStep

    search_algorithm:
        type: BackboneNas
        codec: BackboneNasCodec
        policy:
            num_mutate: 10
            random_ratio: 0.2
        range:
            max_sample: 3 #100
            min_sample: 1 #10

    search_space:
        type: SearchSpace
        modules: ['backbone', 'head']
        backbone:
            ResNetVariant:
                base_depth: [18, 34, 50, 101]
                base_channel: [32, 48, 56, 64]
                doublechannel: [3, 4]
                downsample: [3, 4]
        head:
            LinearClassificationHead:
                num_classes: [10]

    trainer:
        type: Trainer
        epochs: 1

    dataset:
        type: Cifar10
        common:
            data_path: /cache/datasets/cifar10/

fully_train:
    pipe_step:
        type: FullyTrainPipeStep
        models_folder: "{local_base_path}/output/nas/"

    trainer:
        ref: nas.trainer
        epochs: 160
        optim:
            type: SGD
            params:
                lr: 0.1
                momentum: 0.9
                weight_decay: 0.0001
        lr_scheduler:
            type: MultiStepLR
            params:
                milestones: [60, 120]
                gamma: 0.5

    dataset:
        ref: nas.dataset
