general:
    worker:
        devices_per_job: -1

pipeline: [search, retrain]

search:
    pipe_step:
        type: FullyTrainPipeStep

    dataset:
        type: AvazuDataset
        batch_size: 2000
        common:
            data_path: /cache/datasets/Avazu/

    model:
        model_desc:
            modules: ["custom"]
            custom:
                input_dim: 645195
                input_dim4lookup: 24
                embed_dim: 40
                hidden_dims: [700, 700, 700, 700, 700]
                dropout_prob: 0.0
                batch_norm: False
                layer_norm: True
                alpha_init_mean: 0.0
                alpha_activation: 'tanh'
                selected_pairs: []
                name: AutoGateModel
    trainer:
        type: Trainer
        callbacks: AutoGateGrdaS1TrainerCallback
        epochs: 1
        optim:
            type: Adam
            params:
                lr: 0.001
        struc_optim:
            struct_lr: 1
        net_optim:
            net_lr: 1e-3
        c: 0.0004
        mu: 0.75
        lr_scheduler:
            type: StepLR
            params:
                step_size: 1000
                gamma: 0.75
        metric:
            type: auc
        loss:
            type: BCEWithLogitsLoss

    evaluator:
        type: Evaluator
        gpu_evaluator:
            type: GpuEvaluator
            ref: trainer


retrain:
    pipe_step:
        type: FullyTrainPipeStep

    dataset:
        type: AvazuDataset
        batch_size: 2000
        common:
            data_path: /cache/datasets/Avazu/

    model:
        model_desc:
            modules: ["custom"]
            custom:
                input_dim: 645195
                input_dim4lookup: 24
                embed_dim: 40
                hidden_dims: [700, 700, 700, 700, 700]
                dropout_prob: 0.0
                batch_norm: False
                layer_norm: True
                alpha_init_mean: 0.0
                alpha_init_radius: 1e-4
                alpha_activation: 'tanh'
                selected_pairs: []
                name: AutoGateModel
    trainer:
        type: Trainer
        callbacks: AutoGateGrdaS2TrainerCallback
        epochs: 1
        optim:
            type: Adam
            params:
                lr: 0.001
        struc_optim:
            struct_lr: 1
        net_optim:
            net_lr: 1e-3
        c: 0.0004
        mu: 0.75
        lr_scheduler:
            type: StepLR
            params:
                step_size: 1000
                gamma: 0.75
        metric:
            type: auc
        loss:
            type: BCEWithLogitsLoss

    evaluator:
        type: Evaluator
        gpu_evaluator:
            type: GpuEvaluator
            ref: trainer
