general:
    worker:
        devices_per_job: 1

pipeline: [ nas, fully_train ]

nas:
    pipe_step:
        type: NasPipeStep

    search_algorithm:
        type: AutoLaneNas
        codec: AutoLaneNasCodec
        random_ratio: 0.5
        num_mutate: 20
        max_sample: 5000
        min_sample: 50
        flops_ceiling_set_by_GFlops: 1
    search_space:
        type: SearchSpace
        modules: ['backbone', 'neck']
        backbone:
            ResNetVariantDet:
                base_depth: [18, 34, 50, 101]
                base_channel: [32, 48, 56, 64]
            ResNeXtVariantDet:
                base_depth: [18, 34, 50, 101]
                base_channel: [32, 48, 56, 64]
        neck:
            FeatureFusionModule:
                arch_code: ['012-022', '012-122', '122-022','-']

    trainer:
        type: Trainer
        save_model_desc: True
        with_valid: True
        is_detection_trainer: True
        callbacks: ['AutoLaneTrainerCallback','DetectionMetricsEvaluator','DetectionProgressLogger']
        lr_adjustment_position: 'after_train_step'
        report_freq: 50
        valid_interval: 10
        epochs: 40  # truth is 40
        verbose: True
        optim:
            type: SGD
            params:
                lr: 0.02
                momentum: 0.9
                weight_decay: 0.0001
        lr_scheduler:
            type: WarmupScheduler
            params:
                by_epoch: False
                warmup_type: linear
                warmup_iters: 5000
                warmup_ratio: 0.1
                after_scheduler_by_epoch: False
                after_scheduler_config:
                    type: CosineAnnealingLR
                    T_max: 120000 # int(10_0000/batch_size)*epoch-warmup_iters
        metric:
            type: LaneMetric
            params:
                method: f1_measure
                eval_width: 1640
                eval_height: 590
                iou_thresh: 0.5
                lane_width: 30
                thresh_list:  [0.50, 0.60, 0.70, 0.80, 0.90]

    dataset:
        type: AutoLaneDataset
        common:
            network_input_width: 512
            network_input_height: 288
            gt_len: 145
            gt_num: 576
            batch_size: 32
            num_workers: 12
            dataset_file: "/cache/datasets/CULane/dataset.py"
            dataset_format: CULane
        train:
            with_aug: False
            shuffle: True
            random_sample: True
        valid:
            shuffle: False
        test:
            shuffle: False

fully_train:
    pipe_step:
        type: FullyTrainPipeStep
        models_folder: "{local_base_path}/output/nas/"
    trainer:
        type: Trainer
        is_detection_trainer: True
        valid_interval: 100
        callbacks: ['AutoLaneTrainerCallback','DetectionMetricsEvaluator','DetectionProgressLogger']
        report_freq: 50
        epochs: 40  # truth is 40
        verbose: True
        lr_adjustment_position: 'after_train_step'
        optim:
            type: SGD
            params:
                lr: 0.02
                momentum: 0.9
                weight_decay: 0.0001
        lr_scheduler:
            type: WarmupScheduler
            params:
                by_epoch: False
                warmup_type: linear
                warmup_iters: 5000
                warmup_ratio: 0.1
                after_scheduler_by_epoch: False
                after_scheduler_config:
                    type: CosineAnnealingLR
                    T_max: 120000 # int(10_0000/batch_size)*epoch-warmup_iters
        metric:
            type: LaneMetric
            params:
                method: f1_measure
                eval_width: 1640
                eval_height: 590
                iou_thresh: 0.5
                lane_width: 30
                thresh_list:  [0.50, 0.60, 0.70, 0.80, 0.90]

    dataset:
        type: AutoLaneDataset
        common:
            network_input_width: 512
            network_input_height: 288
            gt_len: 145
            gt_num: 576
            batch_size: 32
            num_workers: 12
            dataset_format: CULane
            dataset_file: "/cache/datasets/CULane/dataset.py"
        train:
            with_aug: True
            shuffle: True
            random_sample: True
        valid:
            shuffle: False
        test:
            shuffle: False
