_BASE_: "../Base-RCNN-FPN.yaml"
INPUT:
  FIX_SHAPE: (1280, 768)
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
 MIN_SIZE_TRAIN: (640, 672, 704, 736, 768)
DATALOADER:
  ASPECT_RATIO_GROUPING: False

