general:
    worker:
        devices_per_job: 1

pipeline: [nas, fully_train, benchmark_cifar10]

nas:
    pipe_step:
        type: NasPipeStep

    dataset:
        type: Cifar10
        common:
            data_path: /cache/datasets/cifar10/
            train_portion: 0.9
        train:
            batch_size: 128
        test:
            batch_size: 256

    search_algorithm:
        type: QuantEA
        codec: QuantCodec
        policy:
            length: 40
            num_generation: 50
            num_individual: 16
            random_models: 32

    search_space:
        type: SearchSpace
        modules: ['backbone']
        bit_candidates: [4, 8]
        backbone:
            name: 'QuantResNet'
            num_blocks: [3, 3, 3]
            num_classes: 10

    trainer:
        type: Trainer
        callbacks: QuantTrainerCallback
        epochs: 1
        optim:
            type: SGD
            params:
                lr: 0.1
                momentum: 0.9
                weight_decay: !!float 1e-4
        lr_scheduler:
            type: MultiStepLR
            params:
                milestones: [5, 10, 15]
                gamma: 0.1
        seed: 10
        save_weight: False
        save_model_desc: True
        limits:
            flop_range: [!!float 0, !!float 1e10]

fully_train:
    pipe_step:
        type: FullyTrainPipeStep
        models_folder: "{local_base_path}/output/nas/"
    dataset:
        ref: nas.dataset
        common:
            train_portion: 1
        train:
            shuffle: True

    search_space:
        type: SearchSpace
        modules: ['backbone']
        bit_candidates: [4, 8]
        backbone:
            name: 'QuantResNet'
            num_blocks: [3, 3, 3]
            num_classes: 10

    trainer:
        ref: nas.trainer
        epochs: 400
        lr_scheduler:
            type: MultiStepLR
            params:
                milestones: [200, 300, 375]
                gamma: 0.1

benchmark_cifar10:
    pipe_step:
        type: BenchmarkPipeStep
        models_folder: "{local_base_path}/output/fully_train/"
        record_from: fully_train
    dataset:
        ref: nas.dataset
    evaluator:
        type: Evaluator
        gpu_evaluator:
            type: GpuEvaluator
            metric:
                type: accuracy
