general:
    worker:
        devices_per_job: -1

pipeline: [fully_train]

fully_train:
    pipe_step:
        type: FullyTrainPipeStep

    dataset:
        type: AvazuDataset
        common:
            data_path: /cache/datasets/Avazu/

    model:
        model_desc:
            modules: ["custom"]
            custom:
                input_dim: 645195
                input_dim4lookup: 24
                hidden_dims: [1024, 512, 256, 1]
                dropout_prob: 0.0
                batch_norm: False
                layer_norm: False
                name: AutoGroupModel
                max_order: 3
                embed_dims: [40, 60, 100]
                bucket_nums: [15, 130, 180]
                temperature: 0.01
                lambda_c: 0.01
    trainer:
        type: Trainer
        callbacks: AutoGroupTrainerCallback
        epochs: 1
        optim:
            type: Adam
            params:
                lr: 0.001
        struc_optim:
            struct_lr: 1e2
        net_optim:
            net_lr: 1e-3
        lr_scheduler:
            type: StepLR
            params:
                step_size: 1000
                gamma: 0.75
        metric:
            type: auc
        loss:
            type: BCEWithLogitsLoss

    evaluator:
        type: Evaluator
        gpu_evaluator:
            type: GpuEvaluator
            ref: trainer
