create_algo:
  name: SSD-Ascend-ModelZoo
  description: ""
  config:
    training:
      image:
        engine_name: Ascend-Powered-Engine
        engine_version: Mindspore-1.1.1-python3.7-aarch64
      code:
        relative_boot_file: start.py
      inputs:
        - name: 数据来源
          parameter:
            label: data_url
            value: data_url/
          dataset_enable: false
          annotations:
            - key: data_source
              value:
                - obs
                - modelarts_dataset
            - key: dataset_type
              value:
                - '0'
            - key: data_format
              value:
                - Default
            - key: data_segmentation
              value:
                - ''
            - key: isconstrictinput
            - key: constrictInputTempShow
            - key: isSelectDatasetAndObs
      outputs:
        - name: 模型输出
          description: ''
          parameter:
            label: train_url
            value: train_url/
          artifact:
            - type: ''
          modelarts_hosted: false
      flavor:
        flavor_codes: []
        annotations:
          - key: flavor_type
            value:
              - Ascend
          - key: is_multi_devices_supported
            value:
              - 'true'
          - key: is_multi_nodes_supported
            value:
              - 'true'
          - key: flavor_codes
            value: []
          - key: isMultiDevHide
      parameters:
        regular:
          - key: lr
            help: Learning rate init value
            type: Continuous
            default_value: '0.05'
            editable: true
            required: true
          - key: dataset
            help: Dataset, one of [coco, voc, other], default is coco.
            type: String
            default_value: 'coco'
            editable: true
            required: true
          - key: epoch_size
            help: Epoch size, default is 5.
            type: Integer
            default_value: '5'
            editable: true
            required: true
          - key: batch_size
            help: Batch size, default is 32.
            type: Integer
            default_value: '32'
            editable: true
            required: true
          - key: save_checkpoint_epochs
            help: Save checkpoint epochs, default is 10.
            type: Integer
            default_value: '10'
            editable: true
            required: true
          - key: feature_extractor_base_param
            help: pretrain model path, ssd_mobilenet_v1_fpn need a pretrained model.
            type: String
            default_value: ''
            editable: true
            required: true
          - key: classes_label_path
            help: dataset label file path.
            type: String
            default_value: ''
            editable: true
            required: true
          - key: num_classes
            help: Dataset class number.
            type: Integer
            default_value: "81"
            editable: true
            required: true
          - key: coco_root
            help: COCO2017 dataset path
            type: String
            default_value: ''
            editable: true
            required: true
          - key: voc_root
            help: VOC original dataset path
            type: String
            default_value: ''
            editable: true
            required: true
          - key: voc_json
            help: is the path of json file with coco format for evaluation
            type: String
            default_value: ''
            editable: true
            required: true
          - key: image_dir
            help: Other dataset image path, if coco or voc used, it will be useless
            type: String
            default_value: ''
            editable: true
            required: true
          - key: anno_path
            help: Other dataset annotation path, if coco or voc used, it will be useless
            type: String
            default_value: ''
            editable: true
            required: true
          - key: pre_trained
            help: Pretrained checkpoint file path
            type: String
            default_value: ''
            editable: true
            required: true
          - key: loss_scale
            help: dataset path when dataset is voc.
            type: Integer
            default_value: "1024"
            editable: true
            required: true
          - key: filter_weight
            help: Load parameters in head layer or not. If the class numbers of train dataset is different from the class numbers in pre_trained checkpoint, please set True.
            type: String
            default_value: 'False'
            editable: true
            required: true
          - key: freeze_layer
            help: Freeze the backbone parameters or not, support none and backbone.
            type: String
            default_value: 'none'
            editable: true
            required: true

        customization: true

publish_algo:
  item_name: 目标检测-SSD(Ascend-ModelZoo)
  short_desc: 基于MindSpore, Ascend910训练

create_train_job:
  task_type: object_detection
  job_desc: null
  config:
    flavor:
      code: modelarts.kat1.xlarge
    log_url: null
    parameter:
      - label: epoch_size
        value: '50'
        editable: true
        required: true
      - label: lr
        value: '0.02'
        editable: true
        required: true
    inputs:
      - data_source:
          obs:
            obs_url: null
    outputs:
      - value: null

create_model:
  model_type: MindSpore
  description: null

create_service:
  schedule:
    - duration: 1
      time_units: HOURS
      type: stop
  description: null
  config:
    - specification: modelarts.kat1.xlarge
