export DDK_VERSION_FLAG=1.76.T1.0.B010
export WHICH_OP=GEOP
export NEW_GE_FE_ID=1
export GE_AICPU_FLAG=1
export GE_USE_STATIC_MEMORY=1
export OPTION_EXEC_HCCL_FLAG=1
export HCCL_CONNECT_TIMEOUT=600
export SOC_VERSION=Ascend910

export ASCEND_HOME=/usr/local/Ascend


