algorithm:
  name: "TinyBert"
  framework: "mindspore"
  description:
    zh: "Tinyert 任务蒸馏和通用蒸馏"
    en: "tinybert task distill && general distill"
# 模型训练相关配置
train:
  on_modelarts:
    # 训练入口脚本, 仅支持py脚本
    entry: "on_platform/modelarts/start.py"
    # 每个模型都必须支持的参数
    comm_para:
      input_path:
        # modelarts中的数据集路径name
        - name: "data_url"
          type: "string"
          desc:
            zh: "数据集路径"
            en: "dataset path"
      output_path:
        # modelarts中的数据集路径name
        - name: "train_url"
          type: "string"
          desc:
            zh: "输出路径"
            en: "output path"

    custom_para:
      - name: "distill_type"
        type: "string"
        default: "td"
        choice:
          - "gd"
          - "td"
        required: true
        desc:
          zh: "选择通用蒸馏或任务蒸馏"
          en: "task distill or general distill"
        editable: true

      - name: "device_target"
        type: "string"
        default: "Ascend"
        required: true
        choice:
          - "Ascend"
          - "GPU"
        desc:
          zh: "硬件选择"
          en: "device where the code will be implemented. (Default: Ascend)'"
        editable: true

      - name: "distribute"
        type: "string"
        default: "true"
        choice:
          - "true"
          - "false"
        required: true
        desc:
          zh: "是否分布式"
          en: "Run distribute, default is false."
        editable: true

      - name: "td_do_train"
        type: "string"
        default: "true"
        choice:
          - "true"
          - "false"
        required: false
        desc:
          zh: "是否进行通用蒸馏训练"
          en: "Do train task, default is true."
        editable: true

      - name: "td_do_eval"
        type: "string"
        default: "true"
        choice:
          - "true"
          - "false"
        required: false
        desc:
          zh: "是否进行通用蒸馏评估"
          en: "Do eval task, default is true."
        editable: true

      - name: "td_phase1_epoch_size"
        type: "int"
        default: 10
        required: false
        desc:
          zh: "通用蒸馏第一阶段训练轮数"
          en: "Epoch size for td phase 1, default is 10."
        editable: true

      - name: "td_task_name"
        type: "string"
        default: "SST-2"
        choice:
          - "SST-2"
          - "QNLI"
          - "MNLI"
        required: false
        desc:
          zh: "训练集名称"
          en: "The name of the task to train."
        editable: true

      - name: "td_phase2_epoch_size"
        type: "int"
        default: 3
        required: false
        desc:
          zh: "通用蒸馏第二阶段训练轮数"
          en: "Epoch size for td phase 2, default is 3."
        editable: true

      - name: "td_load_teacher_ckpt_obs"
        type: "str"
        default: ""
        required: false
        desc:
          zh: "在对任务数据集finetune时的断点文件"
          en: "Load bert checkpoint file which finetune in task dataset"
        editable: true

      - name: "td_load_gd_ckpt_obs"
        type: "str"
        default: ""
        required: false
        desc:
          zh: "任务蒸馏步骤：把在通用蒸馏ckpt文件加载入tinybert"
          en: "td step:Load tinybert checkpoint file path which pretrained in gd"
        editable: true

      - name: "td_load_td1_ckpt_obs"
        type: "str"
        default: ""
        required: false
        desc:
          zh: "任务蒸馏步骤：把在任务蒸馏ckpt文件加载入tinybert，用于最后评估"
          en: "td step:Load tinybert checkpoint file path which finetuned in td, used to final eval step"
        editable: true

      - name: "gd_epoch_size"
        type: "int"
        default: 3
        required: false
        desc:
          zh: "通用蒸馏轮数"
          en: "Epoch size, default is 1."
        editable: true
      - name: "gd_device_num"
        type: "int"
        default: 1
        required: false
        desc:
          zh: "通用蒸馏用设备数量"
          en: "Use device nums, default is 1."
        editable: true
      - name: "gd_save_ckpt_path"
        type: "string"
        default: "/tmp/ckpt_save/"
        required: false
        desc:
          zh: "保存ckpt的路径"
          en: "Save checkpoint path"
        editable: true

      - name: "gd_resume_ckpt_obs"
        type: "str"
        default: ""
        required: false
        desc:
          zh: "通用蒸馏断点加载文件"
          en: "resume Load checkpoint file path"
        editable: true

      - name: "gd_load_teacher_ckpt_obs"
        type: "str"
        default: ""
        required: false
        desc:
          zh: "通用蒸馏老师的断点加载文件"
          en: "Load bert checkpoint file path in gd step"
        editable: true

      - name: "do_shuffle"
        type: "string"
        default: "true"
        choice:
          - "true"
          - "false"
        required: false
        desc:
          zh: "是否shuffle"
          en: "Enable shuffle for dataset, default is true."
        editable: true

      - name: "enable_data_sink"
        type: "string"
        default: "true"
        choice:
          - "true"
          - "false"
        required: false
        desc:
          zh: "是否使用数据下沉模式"
          en: "Enable data sink, default is true."
        editable: true

      - name: "save_ckpt_step"
        type: "int"
        default: 100
        required: false
        desc:
          zh: "多少步保存ckpt"
          en: "Steps to save checkpoint."
        editable: true

      - name: "max_ckpt_num"
        type: "int"
        default: 1
        required: false
        desc:
          zh: "最多保存的ckpt数量"
          en: "Maximum checkpoints to be saved."
        editable: true

      - name: "data_sink_steps"
        type: "int"
        default: 1
        required: false
        desc:
          zh: "通用蒸馏中使用，每轮的sink step"
          en: "Sink steps for each epoch, default is 1.used in gd"
        editable: true

      - name: "dataset_type"
        type: "string"
        default: "tfrecord"
        required: false
        desc:
          zh: "数据集类型， tfrecord或mindrecord， 默认tfrecord"
          en: "dataset type tfrecord/mindrecord, default is tfrecord"
        editable: true

      - name: "export_file_format"
        type: "string"
        default: "AIR"
        choice:
          - "AIR"
          - "ONNX"
          - "MINDIR"
        required: false
        desc:
          zh: "转换文件类型"
          en: "export file format"
        editable: true

      - name: "file_name"
        type: "string"
        default: "tinybert"
        required: false
        desc:
          zh: "输出数据名"
          en: "output file name."
        editable: true
