alg_para:
  alg_name: ppo
  alg_config: {
    'prepare_times_per_train': 10,
    # 'BATCH_SIZE': 1280
    }

env_para:
  env_name: atari_env
  env_info: { 'name': BeamRiderNoFrameskip-v4, 'vision': False}

agent_para:
  agent_name: atari_ppo
  agent_num : 1
  agent_config: {
    'max_steps': 128,
    'complete_step': 10000000
    }

model_para:
  actor:
    model_name: ppo_cnn_small
    state_dim: [84,84,4]
    action_dim: 9
    model_config: {
      'LR': 0.00025,
      'LOSS_CLIPPING': 0.1,
      'ENTROPY_LOSS': 0.01
      }

model_name: ppo_beamrider
env_num: 10
node_config: [["127.0.0.1", "username", "passwd"],
              ]

test_model_path: ../xt_train_data/test_model/break_ppo_0516
result_path: ../xt_train_data/test_res/break_ppo_0516_1.csv
