general:
    worker:
        devices_per_job: -1

pipeline: [jdd_search]
# pipeline: [jdd_search, full_train]

jdd_search:
    pipe_step:
        type: NasPipeStep

    dataset:
        type: JDDData
        train:
            root: /cache/datasets/jdd_automl_data/small_train_npz/
            batch_size: 16
            shuffle: true
            pin_memory: True
        test:
            root: /cache/datasets/jdd_automl_data/val_npz/
            batch_size: 1
            shuffle: true
            pin_memory: True

    search_space:
        type: SearchSpace
        modules: ['jddbody']
        jddbody:
            name: JDDNet
            channel_types: ['16', '32', '48']
            channel_prob: [1, 0.5, 0.2]
            block_types: ['R']
            block_prob: [1]
            basic_channel: 16

    search_algorithm:
        type: JDDSearch
        codec: JDDCodec
        policy:
            num_generation: 20
            num_individual: 8
            num_elitism: 4
            mutation_rate: 0.05
        range:
            node_num: 16
            min_active: 6
            min_res_start: 1
            min_res_end: 1
            min_flops: 0
            max_flops: 160000000000
            max_resolutions: 5

    trainer:
        type: Trainer
        callbacks: JDDTrainerCallback
        epochs: 1 #10
        optim:
            type: Adam
            params:
                lr: 0.0001
        lr_scheduler:
            type: MultiStepLR
            params:
                milestones: [100,200]
                gamma: 0.5
        loss:
            type: L1Loss
        metric:
            type: SRMetric
            params:
                method: psnr
        seed: 10

full_train:
    pipe_step:
        type: FullyTrainPipeStep
        models_folder: "{local_base_path}/output/jdd_search/"

    dataset:
        ref: jdd_search.dataset

    trainer:
        ref: jdd_search.trainer
        epochs: 500
        lr_scheduler:
            type: MultiStepLR
            milestones: [300,400]
            gamma: 0.5