ARG FROM_IMAGE_NAME
FROM $FROM_IMAGE_NAME

RUN pip3.7 install --upgrade --no-cache-dir pip3.7 \
 && pip3.7 install --no-cache-dir \
 tqdm boto3 requests six ipdb h5py html2text nltk progressbar onnxruntime