general:
    task:
        local_base_path: /efs-hn/cache/local/
        backup_base_path: s3://automl-hn1/vega/back_up/
    model_zoo:
        model_zoo_path: /efs-hn/cache/model_zoo/
        local_path: ~

Trainer:
    output_model_path: s3://automl-hn1/vega/model_output/

avazu:
    train:
        data_path: /efs-hn/Avazu/

Cifar10:
    train:
        data_path: s3://automl-hn1/Dataset/cifar10/
    val:
        data_path: s3://automl-hn1/Dataset/cifar10/
    test:
        data_path: s3://automl-hn1/Dataset/cifar10/

Cifar100:
    train:
        data_path: s3://automl-hn1/Dataset/cifar100_data/
    val:
        data_path: s3://automl-hn1/Dataset/cifar100_data/
    test:
        data_path: s3://automl-hn1/Dataset/cifar100_data/

Cityscapes:
    train:
        root_path: /efs-hn/cityscapes_dataset/
    test:
        root_path: /efs-hn/cityscapes_dataset/

Coco:
    train:
        data_root: /efs-hn/COCO2017/
        train_ann_file: /efs-hn/COCO2017/annotations/instances_train2017.json
        val_ann_file: /efs-hn/COCO2017/annotations/instances_val2017.json
        test_ann_file: /efs-hn/COCO2017/annotations/instances_val2017.json
        train_img_prefix: /efs-hn/COCO2017/train2017/
        val_img_prefix: /efs-hn/COCO2017/val2017/
        test_img_prefix: /efs-hn/COCO2017/val2017/

DIV2K:
    train:
        root_HR: /efs-hn/DIV2K/div2k_train/hr
        root_LR: /efs-hn/DIV2K/div2k_train/lr
    test:
        root_HR: /efs-hn/DIV2K/div2k_valid/hr
        root_LR: /efs-hn/DIV2K/div2k_valid/lr

Set5:
    test:
        root_HR: /efs-hn/DIV2K/Set5/hr
        root_LR: /efs-hn/DIV2K/Set5/lr

Set14:
    test:
        root_HR: /efs-hn/DIV2K/Set14/hr
        root_LR: /efs-hn/DIV2K/Set14/lr

BSDS100:
    test:
        root_HR: /efs-hn/DIV2K/BSDS100/hr
        root_LR: /efs-hn/DIV2K/BSDS100/lr

UBRAN100:
    test:
        root_HR: /efs-hn/DIV2K/Urban100/hr
        root_LR: /efs-hn/DIV2K/Urban100/lr

FashionMnist:
        train:
            data_path: /efs-hn/fashion_mnist_data/
        val:
            data_path: /efs-hn/fashion_mnist_data/
        test:
            data_path: /efs-hn/fashion_mnist_data/

Imagenet:
    train:
        data_path: /efs-hn/Imagenet/
    val:
        data_path: /efs-hn/Imagenet/
    test:
        data_path: /efs-hn/Imagenet/

Mdc2dDetDataset:
    train:
        train_ann_file: /efs-hn/Mdc2dDetDataset/Vehicle_person/pieline_train_vp.txt
        valid_ann_file: /efs-hn/Mdc2dDetDataset/Vehicle_person/pieline_test_vp.txt
        gt_coco_file: /efs-hn/Mdc2dDetDataset/Vehicle_person/coco_style_file.json
        img_prefix: /efs-hn/Mdc2dDetDataset/Vehicle_person/

Mnist:
    train:
        data_path: s3://automl-hn1/Dataset/mnist/
    val:
        data_path: s3://automl-hn1/Dataset/mnist/
    test:
        data_path: s3://automl-hn1/Dataset/mnist/

CocoDataset:
    train:
        data_root: /efs-hn/COCO2017
        train_ann_file: '/efs-hn/COCO2017/annotations/instances_train2017.json'
        val_ann_file: '/efs-hn/COCO2017/annotations/instances_val2017.json'
        test_ann_file: '/efs-hn/COCO2017/annotations/instances_val2017.json'
        train_img_prefix: '/efs-hn/COCO2017train2017/'
        val_img_prefix: '/efs-hn/COCO2017val2017/'
        test_img_prefix: '/efs-hn/COCO2017val2017/'
    val:
        data_root: /efs-hn/COCO2017
        train_ann_file: '/efs-hn/COCO2017/annotations/instances_train2017.json'
        val_ann_file: '/efs-hn/COCO2017/annotations/instances_val2017.json'
        test_ann_file: '/efs-hn/COCO2017/annotations/instances_val2017.json'
        train_img_prefix: '/efs-hn/COCO2017train2017/'
        val_img_prefix: '/efs-hn/COCO2017val2017/'
        test_img_prefix: '/efs-hn/COCO2017val2017/'
    test:
        data_root: /efs-hn/COCO2017
        train_ann_file: '/efs-hn/COCO2017/annotations/instances_train2017.json'
        val_ann_file: '/efs-hn/COCO2017/annotations/instances_val2017.json'
        test_ann_file: '/efs-hn/COCO2017/annotations/instances_val2017.json'
        train_img_prefix: '/efs-hn/COCO2017train2017/'
        val_img_prefix: '/efs-hn/COCO2017val2017/'
        test_img_prefix: '/efs-hn/COCO2017val2017/'

CurveLaneDataset:
    train:
        data_path: "/efs-hn/Muse/cvpr2020_dataset/dataset.py"
    val:
        data_path: "/efs-hn/Muse/cvpr2020_dataset/dataset.py"
    test:
        data_path: "/efs-hn/Muse/cvpr2020_dataset/dataset.py"
