algorithm:
  name: "DeepFM"
  framework: "mindspore"
  description:
    zh: "基于mindspore的deepfm推荐模型"
    en: "Recommended model named deepfm based on mindspore"
# 模型训练相关配置
train:
  on_modelarts:
    # 训练入口脚本, 仅支持py脚本
    entry: "on_platform/modelarts/start.py"
    # 每个模型都必须支持的参数
    comm_para:
      input_path:
        # modelarts中的数据集路径name
        - name: "data_url"
          type: "string"
          desc:
            zh: "数据集路径"
            en: "dataset path"
      output_path:
        # modelarts中的数据集路径name
        - name: "train_url"
          type: "string"
          desc:
            zh: "输出路径"
            en: "output path"
    custom_para:
      - name: "batch_size"
        type: "int"
        default: 16000
        required: true
        desc:
          zh: "一次训练所抓取的数据样本数量"
          en: "batch size"
        editable: true
      - name: "data_field_size"
        type: "int"
        default: 39
        required: false
        desc:
          zh: "数据集字段数量"
          en: "data's field size"
        editable: true
      - name: "data_vocab_size"
        type: "int"
        default: 184965
        required: false
        desc:
          zh: "数据集词汇数量"
          en: "data's vocab size"
        editable: true
      - name: "train_epochs"
        type: "int"
        default: 15
        required: true
        desc:
          zh: "训练轮数"
          en: "number of training rounds"
        editable: true
      - name: "learning_rate"
        type: "float"
        default: 5e-4
        required: true
        desc:
          zh: "学习率"
          en: "learning rate"
        editable: true
      - name: "resume"
        type: "string"
        default: ""
        required: false
        desc:
          zh: "断点训练模型文件"
          en: "obs path of pretrained deepfm model"
        editable: true
      - name: "do_eval"
        type: "boolean"
        default: "True"
        required: false
        desc:
          zh: "训练时是否评估"
          en: "whether to evaluate during training"
        editable: true
      - name: "device_target"
        type: "string"
        default: "Ascend"
        choice:
          - "Ascend"
          - "GPU"
          - "CPU"
        required: true
        desc:
          zh: "硬件设备,支持Ascend、GPU和CPU"
          en: "device target, support Ascend、GPU and CPU"
        editable: true
