model_name: seq2seq_model
model_params:
  init_scale: 1.0
  initializer: uniform_unit_scaling
  embedding.dim: 32
  src.embedding.initializer: normal
  src.embedding.multiply_mode: sqrt_depth
  tgt.embedding.initializer: normal
  tgt.embedding.multiply_mode: sqrt_depth
  encoder.class: transformer_encoder
  encoder.params:
    num_units: 32
    num_layers: 4
    ffn.num_units: 64
    attention.num_heads: 8
    dropout_rate: 0.1
  decoder.class: transformer_decoder
  decoder.params:
    num_units: 32
    num_layers: 4
    ffn.num_units: 64
    attention.num_heads: 8
    dropout_rate: 0.1
  optimizer.name: LazyAdam
  word_level_loss: true
  learning_rate.constant: 2.0
  max_grad_norm: null
  label_smoothing_factor: 0.1
  learning_rate.warmup_steps: 16000
  learning_rate.schedule: "constant*rsqrt_hidden_size*linear_warmup*rsqrt_decay"
