pipeline: [fully_train, benchmark_cifar10]

fully_train:
    pipe_step:
        type: FullyTrainPipeStep

    dataset:
        type: Cifar10
        common:
            data_path: /cache/datasets/cifar10/
        test:
            batch_size: 256

    model:
        model_desc:
            modules: ["custom"]
            custom:
                name: FmdNetwork
                depth: 56
                num_classes: 10
                args: 
                    drop_prob: 0.03
                    alpha: 5
                    block_size: 6
      
    trainer:
        type: Trainer
        epochs: 200
        seed: 0
        optim:
            type: SGD
            params:
                lr: 0.1
                momentum: 0.9
                weight_decay: 0.0005
        lr_scheduler:
            type: CosineAnnealingLR
            params:
                T_max: 200

benchmark_cifar10:
    pipe_step:
        type: BenchmarkPipeStep
        models_folder: "{local_base_path}/output/fully_train/"
    dataset:
        ref: nas.dataset
    evaluator:
        type: Evaluator
        gpu_evaluator:
            type: GpuEvaluator
            metric:
                type: accuracy
